[package]
name = "advent-of-code-2022"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
text_io = "0.1"
petgraph = "0.6"
serde = "1.0"
serde_json = "1.0"
rayon = "1.6"
pathfinding = "4.1"
itertool = "0.1"
bitflags = "2.0.0-rc.1"